# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [ ]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

weightList = np.array(weight)
heightList = np.array(height)

formula = weightList/(heightList**2) * 730
formula



array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [ ]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example

def matrixMaker(start,end,numbers,shape):
  randomMatrix=np.random.uniform(start,end,numbers)
  randomMatrix=randomMatrix.reshape(shape)

  return randomMatrix

matrixMaker(1,5,6,(2,3))

#     pass

array([[1.92383692, 3.2647787 , 4.58545729],
       [4.51139393, 2.16716913, 1.36585149]])

### #3 - Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np
import itertools

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

red17 = load_data('/content/redsox_2017_hitting.txt')
red18 = load_data('/content/redsox_2018_hitting.txt')


#Test to make sure you have the correct data
print(red17[1:5])
print(red18[1:5])
slg17=red17['SLG']
slg17

[(2, b'1B', b'Mitch Moreland', 31, 149, 576, 508, 73, 125, 34, 0, 22, 79,  0, 1, 57, 120, 0.246, 0.326, 0.443, 0.769,  99, 225, 14)
 (3, b'2B', b'Dustin Pedroia', 33, 105, 463, 406, 46, 119, 19, 0,  7, 62,  4, 3, 49,  48, 0.293, 0.369, 0.392, 0.76 , 100, 159, 11)
 (4, b'SS', b'Xander Bogaerts', 24, 148, 635, 571, 94, 156, 32, 6, 10, 62, 15, 1, 56, 116, 0.273, 0.343, 0.403, 0.746,  95, 230, 17)
 (5, b'3B', b'Rafael Devers', 20,  58, 240, 222, 34,  63, 14, 0, 10, 30,  3, 1, 18,  57, 0.284, 0.338, 0.482, 0.819, 111, 107,  5)]
[(2, b'1B', b'Mitch Moreland', 32, 124, 459, 404, 57,  99, 23, 4, 15,  68, 2, 0, 50, 102, 0.245, 0.325, 0.433, 0.758, 102, 175, 12)
 (3, b'2B', b'Eduardo Nunez', 31, 127, 502, 480, 56, 127, 23, 3, 10,  44, 7, 2, 16,  69, 0.265, 0.289, 0.388, 0.677,  81, 186, 17)
 (4, b'SS', b'Xander Bogaerts', 25, 136, 580, 513, 72, 148, 45, 3, 23, 103, 8, 2, 55, 102, 0.288, 0.36 , 0.522, 0.883, 135, 268, 14)
 (5, b'3B', b'Rafael Devers', 21, 121, 490, 450, 59, 108, 24, 0, 21,  66, 5

array([0.404, 0.443, 0.392, 0.403, 0.482, 0.424, 0.402, 0.459, 0.429,
       0.354, 0.387, 0.333, 0.539, 0.243, 0.262, 0.354, 0.342, 0.339,
       0.328, 0.306, 0.222, 0.2  , 1.   ], dtype=float32)

In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def better_year(cat):
  result=[]
  result17=[]
  result18=[]
  year=0
  slg17=red17[cat]
  slg18=red18[cat]

  for i,k in zip(slg17, slg18):
    if slg17[i] > slg18[k]:
      result17.append(slg17[i])
    elif slg17[i] < slg18[k]:
      result18.append(slg18[k])
    else:
      pass
    
  if len(result17)>len(result18):
    print('Boston 17 had more SLG in 2017 \n')
    result=result17
    year = 17
  elif len(result17)<len(result18):
    print('Boston 18 had more SLG in 2018 \n')
    result=result18
    year = 18
  else:
    print('both years had the same SLG')


  return print('Boston 18 had more SLG in ', year ,'\n',result)
    
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

better_year('SLG')
